Repository unkeyed/unkey, pull requests merged in 2024-11, with the labels that each got.

#2635 fix: "Read the docs button" on /ratelimits page was redirecting users to the home documentation page now after this fix it is redirecting users to specific Rate Limits documentation.
  apps/dashboard/app/(app)/ratelimits/page.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 50 points, hacktoberfest

#2646 docs: fixes the python-sdk docs import statement
  apps/docs/libraries/py/services/apis.mdx
  apps/docs/libraries/py/services/identities.mdx
  apps/docs/libraries/py/services/keys.mdx
  apps/docs/libraries/py/services/migrations.mdx
  apps/docs/libraries/py/services/permissions.mdx
  apps/docs/libraries/py/services/ratelimits.mdx
Labels: Documentation

#2650 docs: add link to Hono OpenAPI description for Mintlify to render as HTML link
  apps/api/src/routes/v1_keys_createKey.ts
Labels: Documentation

#2639 fix: Auditlogs Filters now can be clicked on
  apps/dashboard/app/(app)/audit/[bucket]/filter.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2643 refactor: move discord and github redirects into next configs
  apps/www/app/discord/page.tsx
  apps/www/app/github/page.tsx
  apps/www/next.config.js
Labels: Bug, Needs Approval

#2651 fix: withUnkey should not fail build (@unkey/nextjs)
  .changeset/little-melons-collect.md
  packages/nextjs/src/index.ts
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2645 feat: show disabled in the keys list if key is disabled
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/keys.tsx
Labels: Feature

#2538 fix: bug#2432 Filter options sorted alphabetically
  apps/www/app/templates/client.tsx
Labels: Requires CLA
