Repository unkeyed/unkey, pull requests merged in 2024-12, with the labels that each got.

#2703 fix: Replaced clear button with reset filters button
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/page.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2711 fix: create key toggle issue
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/new/client.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/new/validation.ts
Labels: Bug, Needs Approval

#2717 fix: ratelimit date input and time display logs
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/page.tsx
  apps/dashboard/components/date-time-picker.tsx
Labels: Bug, Needs Approval

#2604 feat: added unkey elysia template
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, hacktoberfest

#2710 fix: Responsiveness issue of ratelimit page
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx
  apps/dashboard/components/dashboard/empty-placeholder.tsx
  apps/dashboard/components/ui/code.tsx
Labels: Needs Approval

#2721 fix: Ensure last ratelimit usage is shown
  apps/chproxy/go.mod
  apps/chproxy/go.sum
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/overrides/table.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx
  apps/dashboard/app/(app)/ratelimits/card.tsx
  internal/clickhouse/src/last_used.ts
  internal/clickhouse/src/ratelimits.ts
Labels: Bug, Needs Approval

#2735 chore: Update footer.tsx
  apps/workflows/src/workflows/count_keys_per_keyspace.ts
  apps/www/components/footer/footer.tsx
Labels: Bug

#2732 fix: Improve the arrangement of metrics in mobile view in ratelimit overview page
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx
Labels: Improvement, Needs Approval

#2768 fix: Removes the secondary search
  apps/dashboard/app/(app)/apis/page.tsx
Labels: Bug, Core Team

#2778 fix: Lint error using onClick on a div #2756
  apps/dashboard/app/(app)/audit/components/filters/filter.tsx
Labels: Bug
