Repository unkeyed/unkey, pull requests merged in 2024-10, with the labels that each got.

#2119 feat: Added support to sidebar
  apps/dashboard/app/(app)/desktop-sidebar.tsx
  apps/dashboard/components/dashboard/command-menu.tsx
  apps/dashboard/components/dashboard/feedback-component.tsx
  pnpm-lock.yaml
Labels: 🕹️ oss.gg, :joystick: 300 points

#2158 chore: update legacy_keys_verifyKey.ts
  apps/api/src/routes/legacy_keys_verifyKey.ts
Labels: 🕹️ oss.gg, :joystick: 50 points

#2165 fix: Sort Permissions
  apps/dashboard/app/(app)/authorization/permissions/page.tsx
Labels: Bug, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2166 docs: README for @unkey/nextjs #2162
  packages/nextjs/README.md
  packages/nextjs/package.json
Labels: Documentation, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2170 fix: dashboard icon flickering
  apps/dashboard/app/(app)/authorization/permissions/page.tsx
  apps/dashboard/app/(app)/desktop-sidebar.tsx
  apps/dashboard/lib/hooks/useDelayLoader.tsx
  packages/ratelimit/package.json
Labels: Bug, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2175 fix: Cal.com link fix
  README.md
  apps/dashboard/app/(app)/settings/billing/plans/page.tsx
  apps/www/components/cta.tsx
  apps/www/components/footer/footer.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2154 fix: align single code block with the buttons
  apps/www/components/blog/blog-code-block.tsx
  apps/www/components/blog/suggested-blogs.tsx
Labels: Feature, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2178 fix(packages/cache): await in redis store
  packages/cache/src/stores/upstash-redis.ts
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2179 fix(billing): add missing subscription fields and audit logging to upgrade flow
  apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx
Labels: Bug, Core Team

#2184 docs: Removing pnpm test:routes
  apps/docs/contributing/testing.mdx
Labels: Documentation, 🕹️ oss.gg, :joystick: 150 points

#2183 fix: revalidate /apis after creating new API
  apps/dashboard/app/(app)/apis/create-api-button.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 50 points, hacktoberfest

#2180 feat: mobile-sidbar-sync-with-desktop
  apps/dashboard/app/(app)/apis/create-api-button.tsx
  apps/dashboard/app/(app)/desktop-sidebar.tsx
  apps/dashboard/app/(app)/layout.tsx
  apps/dashboard/app/(app)/mobile-sidebar.tsx
  apps/dashboard/app/(app)/workspace-navigations.tsx
Labels: Feature, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2200 fix: update go sdk code examples to the current sdk version
  apps/www/app/code-examples.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2212 docs: Fixes a few typos in the docs from revoke to modify / retrieve
  apps/docs/libraries/ex/functions/update_key.mdx
  apps/docs/libraries/ex/functions/update_remaining.mdx
  apps/docs/libraries/ts/sdk/keys/get.mdx
Labels: Documentation, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2214 fix(www): add missing langs to analytics bento
  apps/www/app/code-examples.tsx
  apps/www/components/analytics/analytics-bento.tsx
  apps/www/components/svg/lang-icons.tsx
  apps/www/components/ui/code-editor.tsx
  apps/www/components/ui/copy-code-button.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2223 docs: fix typo and remove the weird line
  apps/docs/libraries/ts/sdk/overview.mdx
Labels: Documentation, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2228 docs: correct spelling of EXPRED to EXPIRED
  apps/docs/api-reference/errors/code/EXPIRED.mdx
Labels: Bug, Documentation, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2240 feat: Follow the Unkey X account
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2229 docs: document pnpm flags in getting started page
  apps/docs/contributing/getting-started.mdx
Labels: Documentation, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2218 feat(dashboard): URL state synchronization for `/settings/root-keys/new` route
  apps/dashboard/app/(app)/settings/root-keys/new/client.tsx
Labels: Feature, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2159 feat: Who Am I route
  .changeset/late-colts-shout.md
  apps/api/src/routes/v1_keys_whoAmI.error.test.ts
  apps/api/src/routes/v1_keys_whoAmI.happy.test.ts
  apps/api/src/routes/v1_keys_whoAmI.security.test.ts
  apps/api/src/routes/v1_keys_whoAmI.ts
  apps/api/src/worker.ts
  apps/docs/api-reference/keys/whoami.mdx
  apps/docs/mint.json
Labels: Feature, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2230 Fix incorrect error code and reference link for UNAUTHORIZED error
  apps/docs/api-reference/errors/code/UNAUTHORIZED.mdx
Labels: Documentation, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2232 fix: add await to mutateAsync function calls
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-enabled.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-expiration.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-name.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-owner-id.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-ratelimit.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-remaining.tsx
  apps/dashboard/app/(app)/apis/[apiId]/settings/update-ip-whitelist.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/settings/update-namespace-name.tsx
  apps/dashboard/app/(app)/settings/general/update-workspace-name.tsx
  apps/dashboard/app/(app)/settings/root-keys/[keyId]/update-root-key-name.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2253 fix(dashboard): hydration warnings
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/delete-permission.tsx
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/page.tsx
  apps/dashboard/app/(app)/authorization/permissions/create-new-permission.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/delete-role.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/update-role.tsx
  apps/dashboard/app/(app)/authorization/roles/create-new-role.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx
  apps/dashboard/app/(app)/ratelimits/sparkline.tsx
  apps/dashboard/app/(app)/semantic-cache/[gatewayId]/analytics/page.tsx
  apps/dashboard/app/(app)/settings/billing/plans/button.tsx
  apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx
  apps/dashboard/app/(app)/settings/root-keys/[keyId]/permissions/permission-manager-card.tsx
  apps/dashboard/app/(app)/settings/vercel/page.tsx
  apps/dashboard/app/(app)/team-switcher.tsx
  apps/dashboard/app/(app)/user-button.tsx
  apps/dashboard/components/dashboard/empty-placeholder.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2272 feat: Create a template with Unkey
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2251 chore: Add error toasts in remaining mutations to handle errors better.
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/client.tsx
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/delete-permission.tsx
  apps/dashboard/app/(app)/authorization/permissions/create-new-permission.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/delete-role.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/update-role.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/overrides/[overrideId]/settings.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/overrides/create-new-override.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/settings/delete-namespace.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/settings/update-namespace-name.tsx
  apps/dashboard/app/(app)/ratelimits/create-namespace-button.tsx
  apps/dashboard/app/(app)/settings/general/update-workspace-name.tsx
  apps/dashboard/components/opt-in.tsx
  apps/dashboard/lib/trpc/routers/ratelimit/deleteNamespace.ts
  apps/dashboard/lib/trpc/routers/ratelimit/updateNamespaceName.ts
  apps/dashboard/lib/trpc/routers/ratelimit/updateOverride.ts
  apps/dashboard/lib/trpc/routers/rbac/deleteRole.ts
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2293 docs: Protecting and Rate Limiting Rust Actix Web API Template
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points

#2284 fix: updating username toast message
  apps/dashboard/app/(app)/settings/user/update-user-name.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2286 chore: Rust + Rocket template [SIDE QUEST]
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2287 chore: add catch block after every db transaction
  apps/dashboard/lib/trpc/routers/api/create.ts
  apps/dashboard/lib/trpc/routers/api/delete.ts
  apps/dashboard/lib/trpc/routers/api/setDefaultBytes.ts
  apps/dashboard/lib/trpc/routers/api/setDefaultPrefix.ts
  apps/dashboard/lib/trpc/routers/api/updateDeleteProtection.ts
  apps/dashboard/lib/trpc/routers/api/updateIpWhitelist.ts
  apps/dashboard/lib/trpc/routers/api/updateName.ts
  apps/dashboard/lib/trpc/routers/key/create.ts
  apps/dashboard/lib/trpc/routers/key/createRootKey.ts
  apps/dashboard/lib/trpc/routers/key/delete.ts
  apps/dashboard/lib/trpc/routers/key/deleteRootKey.ts
  apps/dashboard/lib/trpc/routers/key/updateEnabled.ts
  apps/dashboard/lib/trpc/routers/key/updateExpiration.ts
  apps/dashboard/lib/trpc/routers/key/updateMetadata.ts
  apps/dashboard/lib/trpc/routers/key/updateName.ts
  apps/dashboard/lib/trpc/routers/key/updateOwnerId.ts
  apps/dashboard/lib/trpc/routers/key/updateRatelimit.ts
  apps/dashboard/lib/trpc/routers/key/updateRemaining.ts
  apps/dashboard/lib/trpc/routers/key/updateRootKeyName.ts
  apps/dashboard/lib/trpc/routers/llmGateway/create.ts
  apps/dashboard/lib/trpc/routers/llmGateway/delete.ts
  apps/dashboard/lib/trpc/routers/ratelimit/createNamespace.ts
  apps/dashboard/lib/trpc/routers/ratelimit/createOverride.ts
  apps/dashboard/lib/trpc/routers/ratelimit/deleteNamespace.ts
  apps/dashboard/lib/trpc/routers/ratelimit/deleteOverride.ts
  apps/dashboard/lib/trpc/routers/ratelimit/updateNamespaceName.ts
  apps/dashboard/lib/trpc/routers/ratelimit/updateOverride.ts
  apps/dashboard/lib/trpc/routers/rbac/addPermissionToRootKey.ts
  apps/dashboard/lib/trpc/routers/rbac/connectPermissionToRole.ts
  apps/dashboard/lib/trpc/routers/rbac/connectRoleToKey.ts
  apps/dashboard/lib/trpc/routers/rbac/createPermission.ts
  apps/dashboard/lib/trpc/routers/rbac/createRole.ts
  apps/dashboard/lib/trpc/routers/rbac/deletePermission.ts
  apps/dashboard/lib/trpc/routers/rbac/deleteRole.ts
  apps/dashboard/lib/trpc/routers/rbac/disconnectPermissionFromRole.ts
  apps/dashboard/lib/trpc/routers/rbac/disconnectRoleFromKey.ts
  apps/dashboard/lib/trpc/routers/rbac/removePermissionFromRootKey.ts
  apps/dashboard/lib/trpc/routers/rbac/updatePermission.ts
  apps/dashboard/lib/trpc/routers/rbac/updateRole.ts
  apps/dashboard/lib/trpc/routers/rbac/upsertPermission.ts
  apps/dashboard/lib/trpc/routers/workspace/changeName.ts
  apps/dashboard/lib/trpc/routers/workspace/changePlan.ts
  apps/dashboard/lib/trpc/routers/workspace/create.ts
  apps/dashboard/lib/trpc/routers/workspace/optIntoBeta.ts
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2236 feat: Add profile on mobile top nav
  apps/dashboard/app/(app)/mobile-sidebar.tsx
  apps/dashboard/app/(app)/user-button.tsx
Labels: Feature, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2291 chore: add roadmap link in the footer
  apps/www/app/roadmap/page.tsx
  apps/www/components/footer/footer.tsx
Labels: Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2323 feat: follow unkey on X
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2324 Update 3_follow_the_unkey_x_account.md
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points, hacktoberfest

#2278 fix: transaction ...: in use: for query
  apps/api/src/pkg/audit.ts
Labels: Bug, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2338 Update 3_follow_the_unkey_x_account.md
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2340 fix: weird spacing in changelog by removing the extra gap
  apps/www/components/blog/blog-list.tsx
  apps/www/components/changelog/changelog-grid-item.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2308 docs: add oak & deno sever template with unkey rate limiting
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points

#2315 feat: follow unkey on X #2252
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points, hacktoberfest

#2332 Follow the Unkey X account: @unkeydev Complete!
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2311 fix(www): analytics bento code snippet is not readable
  apps/www/components/analytics/analytics-bento.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2307 feat: Unkey FastAPI boilerplate [SIDE QUEST]
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2357 feat: follow unkey on X
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg

#2301 feat: [🕹️] Record your onboarding and first steps with Unkey
  oss.gg/6_record_onboarding.md
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2316 fix: reset input fields in API delete dialog after reopening
  apps/dashboard/app/(app)/apis/[apiId]/settings/delete-api.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2364 docs: Update Followed unkey on X/twitter
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2371 fix: full width onboarding on md screens
  apps/dashboard/app/new/create-workspace.tsx
Labels: 🕹️ oss.gg

#2384 docs: update overview.mdx
  apps/docs/libraries/ts/cache/overview.mdx
Labels: 🕹️ oss.gg, :joystick: 50 points

#2399 oss.gg side quest 3_follow_the_unkey_x_account.md
  oss.gg/3_follow_the_unkey_x_account.md
Labels: Needs Approval, 🕹️ oss.gg, :joystick: 50 points

#2408 feat: Following unkey acc on twitter #2407
  oss.gg/3_follow_the_unkey_x_account.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#2358 chore: Next.js Pay-as-you-Go starter kit [SIDE QUEST]
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2244 fix: verify-key-status-codes-docs
  apps/api/src/routes/v1_keys_verifyKey.ts
Labels: 🕹️ oss.gg, :joystick: 50 points

#2456 Chore/add line to oss gg file
  oss.gg/3_follow_the_unkey_x_account.md
  oss.gg/4_starry_eyed_supporter.md
Labels: Needs Approval, 🕹️ oss.gg, :joystick: 150 points

#2238 fix: Enhance API Key Detail Page: Change Permissions Visualization to Tree Format
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/page.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/permission-list.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/tree.tsx
  apps/planetfall/app/layout.tsx
  apps/workflows/app/layout.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2273 fix: show shallow permissions followed by nested in alphabetical order
  apps/dashboard/app/(app)/authorization/roles/[roleId]/page.tsx
Labels: Bug, Good first issue, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2362 docs: Protecting TypeScript NestJS Web API Template
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points

#2491 chore: Updated 8 use unkey blog.md
  oss.gg/8_use_unkey_blog.md
Labels: Needs Approval, 🕹️ oss.gg, :joystick: 1500 points

#2294 fix: disable save button when workspace name is empty
  apps/dashboard/app/(app)/settings/general/update-workspace-name.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2379 fix: Missing plan check and ip whitelist parsing
  apps/api/src/pkg/keys/service.ts
  apps/api/src/routes/legacy_keys_verifyKey.test.ts
  apps/api/src/routes/v1_apis_getApi.happy.test.ts
  apps/api/src/routes/v1_keys_verifyKey.test.ts
  apps/dashboard/app/(app)/apis/[apiId]/settings/page.tsx
  apps/dashboard/app/(app)/apis/[apiId]/settings/update-ip-whitelist.tsx
  apps/dashboard/lib/trpc/routers/api/updateIpWhitelist.ts
Labels: Bug, 🕹️ oss.gg, :joystick: 300 points

#2553 fix: update twitter icon to x
  apps/docs/mint.json
Labels: Bug, Needs Approval

#2215 fix: breadcrumb cache issue
  apps/dashboard/app/(app)/@breadcrumb/apis/[apiId]/keys/[keyAuthId]/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/apis/[apiId]/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/apis/[apiId]/settings/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/authorization/permissions/[permissionId]/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/authorization/roles/[roleId]/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/ratelimits/[namespaceId]/logs/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/ratelimits/[namespaceId]/overrides/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/ratelimits/[namespaceId]/page.tsx
  apps/dashboard/app/(app)/@breadcrumb/ratelimits/[namespaceId]/settings/page.tsx
  apps/dashboard/app/(app)/apis/[apiId]/settings/update-api-name.tsx
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/client.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/update-role.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/settings/update-namespace-name.tsx
  apps/dashboard/app/actions.ts
  apps/dashboard/lib/cache.ts
  apps/www/app/glossary/[slug]/page.tsx
  apps/www/app/glossary/client.tsx
  apps/www/components/glossary/search.tsx
  apps/www/components/glossary/terms-rolodex-desktop.tsx
  oss.gg/7_create_a_template.md
  pnpm-lock.yaml
Labels: Bug, 🕹️ oss.gg, :joystick: 300 points, hacktoberfest

#2347 docs: integrated unkey's ratelimiter into my project and wrote a blog post on the same
  oss.gg/7_create_a_template.md
  oss.gg/8_use_unkey_blog.md
Labels: 🕹️ oss.gg, :joystick: 1500 points

#2376 chore: Unkey + Feathers template [SIDE QUEST]
  oss.gg/7_create_a_template.md
Labels: 🕹️ oss.gg, :joystick: 750 points, hacktoberfest

#2330 fix: Pagination Error in Blog Section
  apps/www/components/blog/blog-pagination.tsx
Labels: Bug, Needs Approval

#2568 fix: OAuth Button Loader State Not Reset on Browser Back Navigation.
  apps/dashboard/app/auth/sign-in/oauth-signin.tsx
  apps/dashboard/app/auth/sign-up/oauth-signup.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 50 points

#2546 fix: reset form fields in delete dialog on reopen
  apps/dashboard/app/(app)/authorization/permissions/[permissionId]/delete-permission.tsx
  apps/dashboard/app/(app)/authorization/permissions/create-new-permission.tsx
  apps/dashboard/app/(app)/authorization/roles/[roleId]/delete-role.tsx
  apps/dashboard/app/(app)/authorization/roles/create-new-role.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/settings/delete-namespace.tsx
  apps/dashboard/app/(app)/semantic-cache/[gatewayId]/settings/delete-gateway.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#2542 fix: Client-side exception occurs when adding a filter to rate limit logs table with no data
  apps/dashboard/components/array-input.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2341 fix: Deleting the override doesn't remove it from the overrides. Refreshing it will give you a client side error. #2246
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/overrides/page.tsx
Labels: Requires CLA

#2199 fix: update references from twitter.com to x.com
  apps/api/src/pkg/metrics/axiom.ts
  apps/dashboard/app/auth/layout.tsx
  apps/docs/introduction.mdx
  apps/www/app/changelog/page.tsx
  apps/www/components/changelog/changelog-grid-item.tsx
  apps/www/content/blog/how-unkey-treats-marketing.mdx
  apps/www/content/changelog/2023-07-21.mdx
Labels: Bug, Needs Approval, 🕹️ oss.gg, :joystick: 150 points

#2609 feat(dashboard): remove bottom error from new override form
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/overrides/create-new-override.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 150 points

#2380 fix: Default Bytes should only allow numbers
  apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx
Labels: Bug, 🕹️ oss.gg, :joystick: 50 points

#2618 feat(dashboard): remove tooltip from root key permission toggle
  apps/dashboard/app/(app)/settings/root-keys/[keyId]/permissions/permission-manager-card.tsx
  apps/dashboard/app/(app)/settings/root-keys/new/client.tsx
Labels: Bug, 🕹️ oss.gg
