Repository unkeyed/unkey, pull requests merged in 2025-02, with the labels that each got.

#2857 fix: making pnpm local command to exit if db migration fails
  tools/local/src/db.ts
Labels: Bug, Needs Approval

#2864 fix: modal+dropdown pointer event issue
  apps/dashboard/components/dashboard/root-key-table/index.tsx
  packages/api/package.json
  packages/hono/package.json
  packages/nextjs/package.json
  packages/ratelimit/package.json
Labels: Bug, Good first issue

#2880 chore: Minimum byte length should be consistent
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/new/validation.ts
  apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx
  apps/dashboard/lib/trpc/routers/api/setDefaultBytes.ts
  apps/dashboard/lib/trpc/routers/key/create.ts
Labels: Bug

#2893 fix: Stop whitespace in prefixes and fixes validation on bytes
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/new/validation.ts
  apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx
  apps/dashboard/app/(app)/apis/[apiId]/settings/default-prefix.tsx
  apps/dashboard/lib/trpc/routers/api/setDefaultPrefix.ts
  apps/dashboard/lib/trpc/routers/key/create.ts
Labels: Bug

#2897 fix: updating a key's action should not work when it has been deleted
  apps/api/src/routes/v1_keys_addPermissions.ts
  apps/api/src/routes/v1_keys_addRoles.ts
  apps/api/src/routes/v1_keys_removePermissions.ts
  apps/api/src/routes/v1_keys_removeRoles.ts
  apps/api/src/routes/v1_keys_setPermissions.ts
  apps/api/src/routes/v1_keys_setRoles.ts
  apps/api/src/routes/v1_keys_updateKey.error.test.ts
  apps/api/src/routes/v1_keys_updateKey.ts
  apps/api/src/routes/v1_keys_updateRemaining.ts
Labels: Bug
