Repository unkeyed/unkey, pull requests merged in 2025-03, with the labels that each got.

#2995 fix: hydration errors
  apps/dashboard/app/(app)/apis/_components/create-api-button.tsx
  apps/dashboard/components/keyboard-button.tsx
  apps/dashboard/components/logs/refresh-button/index.tsx
  internal/ui/src/components/tooltip.tsx
Labels: Bug, Needs Approval

#3002 docs: Fix incorrect URL for "Read our blog post" in Zen Readme
  go/pkg/zen/README.md
Labels: Documentation, Needs Approval

#3059 fix(org-selector): force auth page into dark mode
  apps/dashboard/app/auth/sign-in/org-selector.tsx
  apps/dashboard/lib/env.ts
Labels: Bug
