Repository unkeyed/unkey, pull requests merged in 2025-07, with the labels that each got.

#3424 fix: Update Sonner to stop weird behavior, remove props that don't exist from Sonner
  apps/dashboard/app/(app)/apis/[apiId]/_overview/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/_components/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/apis/_components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/audit/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/authorization/permissions/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/authorization/roles/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/logs/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/ratelimits/_components/controls/components/logs-search/index.tsx
  apps/dashboard/app/(app)/settings/root-keys/components/controls/components/root-keys-search/index.tsx
  apps/dashboard/components/ui/toaster.tsx
  apps/dashboard/package.json
  pnpm-lock.yaml
Labels: Bug, Core Team

#3528 fix: chevron position
  apps/dashboard/app/(app)/settings/team/role-switcher.tsx
Labels: Bug

#3636 fix: delete root key returns wrong code
  go/apps/api/routes/v2_apis_delete_api/cache_validation_test.go
  go/apps/api/routes/v2_ratelimit_limit/handler.go
  go/internal/services/keys/get.go
  go/pkg/cache/cache.go
  go/pkg/cache/cache_test.go
  go/pkg/cache/interface.go
  go/pkg/cache/middleware/tracing.go
  go/pkg/cache/noop.go
  go/pkg/cache/simulation_test.go
  go/pkg/cache/swr_test.go
Labels: Bug, Core Team

#3635 fix: upsert ratelimit override
  go/apps/api/routes/v2_ratelimit_set_override/200_test.go
  go/apps/api/routes/v2_ratelimit_set_override/handler.go
  go/pkg/db/bulk_ratelimit_override_insert.sql.go
  go/pkg/db/querier_generated.go
  go/pkg/db/queries/ratelimit_override_insert.sql
  go/pkg/db/ratelimit_override_insert.sql_generated.go
Labels: Bug, Core Team

#3666 fix: remove apiId from verifyKey request
  go/apps/api/openapi/gen.go
  go/apps/api/openapi/openapi-generated.yaml
  go/apps/api/openapi/spec/paths/v2/keys/verifyKey/V2KeysVerifyKeyRequestBody.yaml
  go/apps/api/openapi/spec/paths/v2/keys/verifyKey/V2KeysVerifyKeyResponseBody.yaml
  go/apps/api/openapi/spec/paths/v2/keys/verifyKey/V2KeysVerifyKeyResponseData.yaml
  go/apps/api/openapi/spec/paths/v2/keys/verifyKey/index.yaml
  go/apps/api/routes/v2_keys_verify_key/200_test.go
  go/apps/api/routes/v2_keys_verify_key/400_test.go
  go/apps/api/routes/v2_keys_verify_key/401_test.go
  go/apps/api/routes/v2_keys_verify_key/403_test.go
  go/apps/api/routes/v2_keys_verify_key/404_test.go
  go/apps/api/routes/v2_keys_verify_key/412_test.go
  go/apps/api/routes/v2_keys_verify_key/handler.go
  go/apps/api/routes/v2_keys_verify_key/multilimit_test.go
  go/apps/api/routes/v2_keys_verify_key/ratelimit_response_test.go
  go/internal/services/keys/options.go
  go/internal/services/keys/status.go
  go/internal/services/keys/verifier.go
Labels: Core Team
